//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_1> Table_1 { get; set; }
    
        public virtual ObjectResult<Order001> GetOrder01()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order001>("GetOrder01");
        }
    
        public virtual ObjectResult<Order002> GetOrder02()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order002>("GetOrder02");
        }
    
        public virtual ObjectResult<Order003> GetOrder03()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order003>("GetOrder03");
        }
    
        public virtual ObjectResult<Order004> GetOrder04()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order004>("GetOrder04");
        }
    
        public virtual ObjectResult<Order005> GetOrder05()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order005>("GetOrder05");
        }
    
        public virtual ObjectResult<Order006> GetOrder06()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order006>("GetOrder06");
        }
    
        public virtual ObjectResult<Order007> GetOrder07()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order007>("GetOrder07");
        }
    
        public virtual ObjectResult<Order008> GetOrder08()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order008>("GetOrder08");
        }
    
        public virtual ObjectResult<Order009> GetOrder09()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order009>("GetOrder09");
        }
    
        public virtual ObjectResult<Order010> GetOrder10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order010>("GetOrder10");
        }
    
        public virtual ObjectResult<Order011> GetOrder11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order011>("GetOrder11");
        }
    
        public virtual ObjectResult<Order012> GetOrder12()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order012>("GetOrder12");
        }
    
        public virtual ObjectResult<Order013> GetOrder13()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order013>("GetOrder13");
        }
    
        public virtual ObjectResult<Order014> GetOrder14()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order014>("GetOrder14");
        }
    
        public virtual ObjectResult<Order015> GetOrder15()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order015>("GetOrder15");
        }
    
        public virtual ObjectResult<Order016> GetOrder16()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order016>("GetOrder16");
        }
    
        public virtual ObjectResult<Order017> GetOrder17()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order017>("GetOrder17");
        }
    
        public virtual ObjectResult<Order018> GetOrder18()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order018>("GetOrder18");
        }
    }
}
