//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int Id { get; set; }
        public string Exercise { get; set; }
        public double RM15 { get; set; }
        public double WI15 { get; set; }
        public double RM10 { get; set; }
        public double WI10 { get; set; }
        public double RM5 { get; set; }
        public double WI5 { get; set; }
    }
}
